# Generated by Django 2.0.2 on 2018-02-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0002_coursemanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseManager',
            new_name='CourseAppManager',
        ),
    ]
