# Generated by Django 2.0.2 on 2018-02-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0003_auto_20180212_1755'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseAppManager',
            new_name='CourseManager',
        ),
    ]
