# Generated by Django 2.0.2 on 2018-02-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0004_auto_20180212_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseManager',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='desciption',
            new_name='description',
        ),
    ]
