# Generated by Django 2.0.2 on 2018-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0006_auto_20180213_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coursesapp/images', verbose_name='Imagem'),
        ),
    ]
